export const surpriseMePrompts = [
    'an armchair in an avocado',
    'a surrealist of a cat playing checkers',
    'teddy bears shopping for groceries',
    'an oil painting by Matisse of a robot',
    'panda mad scientist art',
    "a macro 35mm photograph",
    '3D render of a cute tropical fish',
    'an astronaut lounging in a tropical resort',
    'an oil painting portrait of a capybara',
    'a stained glass window depicting a hamburger',
    'a pencil and watercolor drawing of a city',
    'a sunlit indoor lounge area with a pool',
    'a fortune-telling shiba inu reading a book',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the sea',
    'Two futuristic towers with a skybridge',
    'A 3D render of a rainbow colored hot air balloon',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder',
    'A photo of a Samoyed dog with its tongue out',
    'A photo of a white fur monster in a purple room',
    "A photo of Michelangelo's sculpture of David",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along expressway',
    'A realistic photograph of a young woman',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon',
    'A BBQ that is alive, in the style of a Pixar movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer',
    'A photograph of a cyborg exploring Tokyo',
    'Dracula walking down New York City',
    'Synthwave aeroplane',
    'A man wanders through Tokyo',
    'A Space Shuttle flying above Cape Town',
  ];